// 由 scripts/gen-tokens.mjs 生成 —— 禁止手工编辑
export const TOKENS = {
  tier1: {
    "color.paper": "#FBF8F6",
    "color.paper-warm": "#F4EDE8",
    "color.paper-deep": "#E9DFD8",
    "color.blue": "#7FB6D9",
    "color.blue-deep": "#4E88AE",
    "color.blue-press": "#3E6F92",
    "color.blue-tint": "#E8F1F8",
    "color.blue-ink": "#22333D",
    "color.pink": "#F2A9B8",
    "color.pink-deep": "#E0829A",
    "color.pink-tint": "#FADDE3",
    "color.pink-ink": "#4A2C33",
    "color.ink": "#2B2622",
    "color.ink-soft": "#5C5347",
    "color.ink-faint": "#8C8172",
    "color.hairline": "#E3D8D0",
    "color.hairline-strong": "#C4B3A8",
    "color.accent": "#4E88AE",
    "color.accent-deep": "#3E6F92",
    "color.danger": "#A8321E",
    "color.warn": "#C9862B",
    "color.ok": "#4A7A56",
    "font.display": "LXGWWenKai, 'Source Han Serif SC', 'Songti SC', serif",
    "font.body": "'PingFang SC', 'HarmonyOS Sans SC', 'Microsoft YaHei', system-ui, sans-serif",
    "font.mono": "'JetBrains Mono', ui-monospace, monospace",
    "radius.sm": "4px",
    "radius.md": "10px",
    "radius.lg": "16px",
    "space.0": "0",
    "space.1": "2px",
    "space.2": "4px",
    "space.3": "8px",
    "space.4": "12px",
    "space.5": "16px",
    "space.6": "20px",
    "space.7": "24px",
    "space.8": "32px",
    "space.9": "40px",
    "space.10": "48px",
    "space.12": "64px",
    "space.16": "96px",
    "duration.fast": "120ms",
    "duration.base": "220ms",
    "duration.slow": "400ms",
    "easing.out-soft": "cubic-bezier(.22,.61,.36,1)",
    "easing.in-out-soft": "cubic-bezier(.65,.05,.36,1)",
    "easing.spring": "cubic-bezier(.34,1.56,.64,1)",
  },
  tier2: {
    "surface": "#FBF8F6",
    "surface-raised": "#F4EDE8",
    "surface-sunken": "#E9DFD8",
    "text-primary": "#2B2622",
    "text-secondary": "#5C5347",
    "text-tertiary": "#8C8172",
    "text-inverse": "#FBF8F6",
    "border": "#E3D8D0",
    "border-strong": "#C4B3A8",
    "brand": "#4E88AE",
    "brand-deep": "#3E6F92",
    "heart": "#F2A9B8",
    "heart-deep": "#E0829A",
    "font-role": "LXGWWenKai, 'Source Han Serif SC', 'Songti SC', serif",
    "font-user": "'PingFang SC', 'HarmonyOS Sans SC', 'Microsoft YaHei', system-ui, sans-serif",
  },
  tier3: {
    "bubble-user-bg": "#FADDE3",
    "bubble-user-fg": "#4A2C33",
    "bubble-user-radius": "12px 12px 2px 12px",
    "bubble-role-bg": "#E8F1F8",
    "bubble-role-fg": "#22333D",
    "bubble-role-radius": "12px 12px 12px 2px",
    "composer-bg": "#FBF8F6",
    "composer-border": "#C4B3A8",
    "nav-bg": "#F4EDE8",
    "button-primary-bg": "#3E6F92",
    "button-primary-fg": "#FBF8F6",
    "quote-font": "LXGWWenKai, 'Source Han Serif SC', 'Songti SC', serif",
    "quote-letter-spacing": "0.01em",
    "texture-paper-opacity": "0.35",
    "elev-raise": "0 1px 2px rgba(43,38,34,.06), 0 2px 8px rgba(43,38,34,.05)",
    "elev-float": "0 4px 16px rgba(43,38,34,.10), 0 12px 32px rgba(43,38,34,.08)",
  },
} as const;

export type TokenKey = keyof typeof TOKENS.tier1 & keyof typeof TOKENS.tier2 & keyof typeof TOKENS.tier3;
